lab5/Lab5/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lab5.Models
{
    public class Hospital
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }
        public string Phones { get; set; }
        public ICollection<Doctor> Doctors { get; set; }
    }
}

lab5/Lab5/ViewModels/Hospitals/HospitalCreatingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.ViewModels.Hospitals
{
    public class HospitalCreatingViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }

        public string Phones { get; set; }
    }
}

lab5/Lab5/ViewModels/Hospitals/HospitalEditingViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Lab5.ViewModels.Hospitals
{
    public class HospitalEditingViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }

        public string Phones { get; set; }
    }
}

lab5/Lab5/Controllers/DoctorsController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Lab5.Models;
using Microsoft.AspNetCore.Mvc;
using Lab5.ViewModels.Doctors;
using Microsoft.EntityFrameworkCore;

namespace Lab5.Controllers
{
    public class DoctorsController : Controller
    {
        private ApplicationDbContext _db;

        public DoctorsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _db.Doctors.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var hospitals = await _db.Hospitals
                .Select(h => new {h.Id, h.Name})
                .ToListAsync();

            var model = new DoctorCreatingViewModel
            {
                Hospitals = hospitals.Select(h => (h.Id, h.Name))
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DoctorCreatingViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.HospitalId != null)
                {
                    var hospital = await _db.Hospitals
                        .FirstOrDefaultAsync(h => h.Id == model.HospitalId);

                    if (hospital == null)
                    {
                        ModelState.AddModelError("HospitalId", "Hospital was not found");
                        goto Err;
                    }
                }

                _db.Doctors.Add(new Doctor()
                {
                    Name = model.Name,
                    Speciality = model.Speciality,
                    HospitalId = model.HospitalId
                });
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            Err:
            var hospitals = await _db.Hospitals
                .Select(h => new { h.Id, h.Name })
                .ToListAsync();

            model.Hospitals = hospitals.Select(h => (h.Id, h.Name));
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (ModelState.IsValid)
            {
                var doctor = await _db.Doctors.FirstOrDefaultAsync(d => d.Id == id);

                if (doctor is null)
                    return NotFound();

                var hospitals = await _db.Hospitals
                    .Select(h => new { h.Id, h.Name })
                    .ToListAsync();

                var model = new DoctorEditingViewModel
                {
                    Id = id,
                    Name = doctor.Name,
                    Speciality = doctor.Speciality,
                    HospitalId = doctor.HospitalId,
                    Hospitals = hospitals.Select(h => (h.Id, h.Name))
                };

                return View(model);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DoctorEditingViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.HospitalId != null)
                {
                    var hospital = await _db.Hospitals.FirstOrDefaultAsync(h => h.Id == model.HospitalId);
                    if (hospital is null)
                        return BadRequest("Hospital is not exist");
                }

                _db.Doctors.Update(new Doctor
                {
                    Id = model.Id,
                    Name = model.Name,
                    Speciality = model.Speciality,
                    HospitalId = model.HospitalId
                });
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            var hospitals = await _db.Hospitals
                .Select(h => new { h.Id, h.Name })
                .ToListAsync();

            model.Hospitals = hospitals.Select(h => (h.Id, h.Name));
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            if (ModelState.IsValid)
            {
                var doctor = await _db.Doctors.FirstOrDefaultAsync(d => d.Id == id);

                if (doctor is null)
                    return NotFound();

                _db.Doctors.Remove(doctor);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        public async Task<IActionResult> Details([Required] Guid id)
        {
            if (ModelState.IsValid)
            {
                var doctor = await _db.Doctors.Include(d => d.Hospital)
                    .FirstOrDefaultAsync(d => d.Id == id);

                if (doctor is null)
                {
                    return NotFound();
                }

                return View(doctor);
            }

            return BadRequest();
        }
    }
}

lab5/Lab5/Controllers/HospitalsController.cs
using System;
using System.Threading.Tasks;
using Lab5.Models;
using Lab5.ViewModels.Hospitals;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab5.Controllers
{
    public class HospitalsController : Controller
    {
        private ApplicationDbContext _db;
        public HospitalsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Hospitals.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(HospitalCreatingViewModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Hospitals.Add(new Hospital()
                {
                    Name = model.Name,
                    Address = model.Address,
                    Phones = model.Phones
                });
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (ModelState.IsValid)
            {
                var hospital = await _db.Hospitals.Include(h => h.Doctors)
                    .FirstOrDefaultAsync(h => h.Id == id);

                if (hospital is null)
                    return NotFound();

                return View(hospital);
            }

            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (ModelState.IsValid)
            {
                var hospital = await _db.Hospitals.FirstOrDefaultAsync(h => h.Id == id);

                if (hospital is null)
                    return NotFound();

                var model = new HospitalEditingViewModel
                {
                    Id = hospital.Id,
                    Name = hospital.Name,
                    Address = hospital.Address,
                    Phones = hospital.Phones
                };

                return View(model);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HospitalEditingViewModel model)
        {
            if (ModelState.IsValid)
            {
                _db.Hospitals.Update(new Hospital
                {
                    Id = model.Id,
                    Name = model.Name,
                    Address = model.Address,
                    Phones = model.Phones
                });
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            if (ModelState.IsValid)
            {
                var hospital = await _db.Hospitals.FirstOrDefaultAsync(h => h.Id == id);

                if (hospital is null)
                    return NotFound();

                _db.Hospitals.Remove(hospital);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return BadRequest();
        }
    }
}

lab5/Lab5/Views/Hospitals/Create.cshtml
@model Lab5.ViewModels.Hospitals.HospitalCreatingViewModel
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>
<h3>Hospital</h3>
<form asp-controller="Hospitals" asp-action="Create">
    <div class="validation" asp-validation-summary="ModelOnly"></div>

    <!-- Name -->
    <div class="form-group">
        <label asp-for="Name" class="font-weight-bold"></label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name"></span>
    </div>
    
    <!-- Address -->
    <div class="form-group">
        <label asp-for="Address" class="font-weight-bold"></label>
        <input asp-for="Address" class="form-control"/>
        <span asp-validation-for="Address"></span>
    </div>
    
    <!-- Phones -->
    <div class="form-group">
        <label asp-for="Phones" class="font-weight-bold"></label>
        <input asp-for="Phones" class="form-control"/>
        <span asp-validation-for="Phones"></span>
    </div>
    
    <!-- Submit -->
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

lab5/Lab5/Views/Hospitals/Details.cshtml
@model Lab5.Models.Hospital
@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>
<dl class="container">
    <!-- Name -->
    <div class="row form-group">
        <dt class="col-sm-3 text-sm-right font-weight-bold">Name</dt>
        <dd class="col-sm-3 text-secondary">@Model.Name</dd>
    </div>

    <!-- Address -->
    <div class="row form-group">
        <dt class="col-sm-3 text-sm-right font-weight-bold">Address</dt>
        <dd class="col-sm-3 text-secondary">@Model.Address</dd>
    </div>

    <!-- Phones -->
    <div class="row form-group">
        <dt class="col-sm-3 text-sm-right font-weight-bold">Phones</dt>
        <dd class="col-sm-3 text-secondary">@Model.Phones</dd>
    </div>

    <!-- Doctors -->
    <div class="row form-group">
        <dt class="col-sm-3 text-sm-right font-weight-bold">Doctors</dt>
        <div class="col-sm-3">
            @foreach (var doctor in Model.Doctors)
            {
                <a asp-controller="Doctors" asp-action="Details" asp-route-id="@doctor.Id">
                    @doctor.Name,
                </a>
            }
        </div>

    </div>
</dl>

lab5/Lab5/Views/Hospitals/Edit.cshtml
@model Lab5.ViewModels.Hospitals.HospitalEditingViewModel
@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>
Hospital
<form asp-controller="Hospitals" asp-action="Edit" asp-route-id="@Model.Id">
    <div class="validation" asp-validation-summary="ModelOnly"></div>

    <!-- Name -->
    <div class="form-group">
        <label asp-for="Name" class="font-weight-bold"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>

    <!-- Address -->
    <div class="form-group">
        <label asp-for="Address" class="font-weight-bold"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address"></span>
    </div>

    <!-- Phones -->
    <div class="form-group">
        <label asp-for="Phones" class="font-weight-bold"></label>
        <input asp-for="Phones" class="form-control" />
        <span asp-validation-for="Phones"></span>
    </div>

    <!-- Submit -->
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

lab5/Lab5/Views/Hospitals/Index.cshtml
@using Lab5.Models
@model IEnumerable<Lab5.Models.Hospital>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<a asp-controller="Hospitals" asp-action="Create">Create</a>
<table class="table">
    <tr>
        <th>@nameof(Hospital.Name)</th>
        <th>@nameof(Hospital.Address)</th>
    </tr>
    @foreach (var hospital in Model)
    {
        <tr>
            <td>@hospital.Name</td>
            <td>@hospital.Address</td>
            <td>
                <a asp-controller="Hospitals" asp-action="Details" asp-route-id="@hospital.Id">Details</a> |
                <a asp-controller="Hospitals" asp-action="Edit" asp-route-id="@hospital.Id">Edit</a> |
                <a asp-controller="Hospitals" asp-action="Delete" asp-route-id="@hospital.Id">Delete</a>
            </td>
        </tr>
    }
</table>